coin-server에 fcm push 코드 옮기기
sejong-interface/2018-Winter-Project pull request #20
Opened 2019-02-13 08:55 UTC by 2kyung19

PR #18 coin-server에 fcm push 코드 옮기기가 머지되었길래 다시 pr올립니다.

### PR#18 리뷰 정리 및 피드백
@parkjonghyeob 
* <del>FcmController 클래스명 변경</del>
```
FcmController > NotificationController
```
* jsonobject 부분 controller > service에서 처리
```
service.AndroidPushPeriodicNotifications 클래스 생성
```
* <del>calender > LocalDate</del>
* <del>String Day = ""; 불필요</del>
* <del>요일 비교에서 if문 > switch-case문</del>
```
date 메소드를 삭제하고, localDate.getDayOfWeek().name() 로 처리
```
* <del>@RequsetMapping > @GetMapping</del>
* <del>불필요한 주석, line blank, line break 제거</del>
* controller에서 json object 안만들고 object return
> json object코드부분만 위치변경한거라 controller에선 string으로 받지만 결국 기존 코드와 동일합니다.
> data를 생성할 때 json object를 만들지 않고 data를 바로 string으로 생성 한다는 것인가요?
* convention 지키기
> 코드에서 컨벤션지킨다는게 어떤 뜻인지 모르겠습니다..ㅠㅠ

2019-02-13 09:34 UTC, riyenas0925 commented
@2kyung19 코딩컨벤션
원문 : https://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html
번역 : http://kwangshin.pe.kr/blog/java-code-conventions-자바-코딩-규칙/

2019-02-13 09:41 UTC, riyenas0925 commented
@2kyung19 저번에 올려주신거 참고하면 될듯 ㅇㅇ
[Oracle Code Conventions.pdf](https://github.com/sejong-interface/2019-Winter-Project/files/2859707/Oracle.Code.Conventions.pdf)

2019-02-14 01:02 UTC, parkjonghyeob requested changes

2019-02-14 01:02 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/controller/NotificationController.java
> +    @GetMapping(value = "/send", produces = "application/json")
RestController 의 기본 produces 가 application/json 이라 produces 는 없어도 돼~

2019-02-14 01:02 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/controller/NotificationController.java
> +            e.printStackTrace();
단순히 e.printStackTrace() 로 남기지 말고 예외처리를 명확히~
ResponseEntity 를 오류 관련으로 넘기거나 하면 될듯

2019-02-14 01:02 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/controller/NotificationController.java
> +    public @ResponseBody ResponseEntity<String> send() throws JSONException {
Response 객체를 String 으로 하지 말고 Model 로 하면 알아서 Serialize 해줌

2019-02-14 01:02 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/controller/NotificationController.java
> +    AndroidPushNotificationsService androidPushNotificationsService;
private final

2019-02-20 14:37 UTC, 2kyung19 commented
@parkjonghyeob @kimhanui @parkjonghyeob 
* 알림 주기 설정용 어노테이션 scheduled 추가
    * 현재 5초마다 1번 씩 알림
    * 24시간 ( 1000 * 60 * 60 * 24 )
* firebase server key 이용 주석
* json object body 출력 ( 확인용 )

2019-02-20 14:38 UTC, 2kyung19 commented
@riyenas0925 참고 하시유

2019-02-20 14:42 UTC, kimhanui submitted a review, later dismissed

2019-02-20 16:57 UTC, kimhanui commented on coin-server/src/main/java/kr/or/teamserver/coinserver/controller/NotificationController.java
> +    public @ResponseBody ResponseEntity<String> send() throws JSONException {
이게 무슨 의민지 잘 모르겠어요....ㅎ"a 저 send()에서는 Serialize해주지 않은 건가요? 그리고 여기서 말씀하신 모델이 어떤 모델인지 잘 모르겠는데 Washer 모델을 쓰는 건가요? 아니면 Model 클래스를 따로 하나 더 만들어야 하나요?

2019-02-23 12:06 UTC, parkjonghyeob commented
@2kyung19 소스를 하나로 합쳐서 다시 push 해줄 수 있을까?

2019-02-23 14:43 UTC, 2kyung19 commented
코드 업데이트하고 다시 pull request하겠습니다:)

2019-02-23 15:22 UTC, closed without merging