H2 데이터베이스 연결 초기화, 디바이스 토큰, 요일 저장 CRUD 기능 추가
sejong-interface/2018-Winter-Project pull request #21
Opened 2019-02-13 13:05 UTC by riyenas0925

기능
* jdbcTemplate 사용
* H2 in memory 데이터베이스 사용
* 안드로이드 디바이스 CRUD 기능 추가

추가
* H2 데이터베이스 초기 설정 (resources/*)
```mysql
//data.sql
INSERT INTO device(token, date) VALUES ('6dsf2dfsdf6sdfsd6ffsdf', '화');
INSERT INTO device(token, date) VALUES ('5da56sd56asd1sda56dw6a', '금');
```

```mysql
//schema.sql
create table device (
   id int auto_increment primary key,
   token varchar(200) not null,
   date varchar(200) not null,
);
```
* DeviceDAO, DeviceService

2019-02-14 01:03 UTC, parkjonghyeob commented
@riyenas0925 IntegrationTest 는 아래 URL 참고
https://www.baeldung.com/spring-boot-testing

2019-02-14 01:09 UTC, parkjonghyeob requested changes

2019-02-14 01:09 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/persistence/DeviceDAOImpl.java
> +    private JdbcTemplate jdbcTemplate;
private final

2019-02-14 01:09 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/persistence/DeviceDAOImpl.java
> +        return jdbcTemplate.update("INSERT INTO device(token, date) VALUES (?, ?)", "fdfdfdf", "fsdfsdfsdf");
쿼리를 소스에서 직접 넣지 않도록 처리.
JPA 가 편하긴 한데, Mybatis 적용을 고려해봐 줘~

2019-02-14 01:09 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/persistence/DeviceDAOImpl.java
> +    public List<DeviceDto> listAll(){
repository (Dao) 와 연결된 것은 Dto 가 아닌 Model 로 정의

2019-02-14 01:09 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/service/DeviceServiceImpl.java
> +    public Integer createDevice(String token, String date){
DeviceService 라 method 에 굳이 Device 는 안써도 될 듯

2019-02-16 07:54 UTC, parkjonghyeob requested changes

2019-02-16 07:54 UTC, parkjonghyeob commented on coin-server/pom.xml
> +        </dependency>
사용하지 않는 라이브러리 제거

2019-02-16 07:54 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/model/Device.java
> +@Table(name = "tbl_device")
tbl, prefix 제거

2019-02-16 07:54 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/model/Device.java
> +    public Device(){
불필요

2019-02-16 07:54 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/model/Device.java
> +    public Device(String token, String date){
생성자는 전체 필드를 위한 것 하나만 사용하고, 나머진 static factory method 사용

2019-02-16 07:54 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/model/Device.java
> +    private String date;
Date 는 String 이 아니고 LocalDateTime 사용.
name 은 정확한 의미를 지니게

2019-02-16 07:54 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/model/Device.java
> +    private Long id;
primitive type 으로

2019-02-16 07:54 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/service/DeviceServiceImpl.java
> +        if(optionalDevice.isPresent()) {
`if (option......)`

2019-02-16 07:54 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/service/DeviceServiceImpl.java
> +        return new Device();
이렇게 할거면 그냥 Optional<Device> 를 리턴

2019-02-16 07:54 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/service/DeviceServiceImpl.java
>  public class DeviceServiceImpl implements DeviceService {
메서드별로 기본적인 로깅 추가

2019-02-16 07:54 UTC, parkjonghyeob commented on coin-server/src/main/resources/application.properties
> +logging.level.org.hibernate=info
테스트니까 쿼리도 로깅되게 수정

2019-02-16 07:54 UTC, parkjonghyeob commented on coin-server/src/test/java/kr/or/teamserver/coinserver/service/DeviceServiceImplTest.java
> +        deviceDAO = Mockito.mock(DeviceDAO.class);
`import static` 사용

2019-02-16 07:54 UTC, parkjonghyeob commented on coin-server/src/test/java/kr/or/teamserver/coinserver/service/DeviceServiceImplTest.java
> +        Mockito.verify(deviceDAO, Mockito.times(1)).save(Mockito.any(Device.class));
times(1) 은 default 라 없어도 됨
이왕 만든 테스트 코드이니 모든 메서드에 대해서 테스트 코드 추가

2019-02-16 14:49 UTC, riyenas0925 commented
@parkjonghyeob 수정 했습니다!

수정
* sql query logging 추가
* 생성자는 전체 필드 하나만, 나머지는 static factory method로 변경
* device/id 검색시 null이 반환될 경우 exception 추가
* application 실행시 H2 DB 테스트 데이터 삽입
* DeviceServiceImplTest 코드 추가

2019-02-18 10:01 UTC, parkjonghyeob requested changes

2019-02-18 10:01 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/controller/AndroidController.java
> +        }
요건 deviceService 에서 처리.

2019-02-18 10:01 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/controller/ExceptionHandlingController.java
> +
Body 가 없네~

2019-02-18 10:01 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/exception/DeviceNotFound.java
> +@ResponseStatus(value=HttpStatus.NOT_FOUND, reason="No such Order")  // 404
요건  ExceptionHandler에 붙이고 여기에선 제거

2019-02-18 10:01 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/model/Device.java
> +    public Device(Long id, String token, LocalDateTime registDate){
여기 상단에 @PersistenceConstructor 를 사용하고 default constructor 제거

2019-02-18 10:01 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/model/Device.java
> +    // TODO of 네이밍 이유
주석제거

2019-02-18 10:01 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/model/Device.java
hashcode 와 equals 를 override 해서 구현 (이유는 검색)

2019-02-18 10:01 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/service/DeviceServiceImpl.java
> +        deviceDAO.save(Device.of(token));
method 내에 기본적인 로깅 추가

2019-02-18 10:01 UTC, parkjonghyeob commented on coin-server/src/test/java/kr/or/teamserver/coinserver/service/DeviceServiceImplTest.java
> +        }
doThrow...when 처리

2019-02-18 10:01 UTC, parkjonghyeob commented on coin-server/src/test/java/kr/or/teamserver/coinserver/service/DeviceServiceImplTest.java
> +            verify(deviceDAO).save(any(Device.class));
별도의 테스트로

2019-02-20 08:03 UTC, riyenas0925 commented
수정
* update 테스트 별도의 테스트로 변경
* read테스트 doTrow..when으로 처리
* DeviceServiceImpl 내의 method 내에 기본적인 로깅 추가
* Device equals, hashcode추가

* ```@PersistenceConstructor```를 붙여도 default 생성자가 없으면 오류가 발생해서 default constructor을 우선은 안지웠습니다...

2019-02-22 05:57 UTC, parkjonghyeob approved these changes
수고 많았어~!!

2019-02-22 05:57 UTC, parkjonghyeob commented on coin-server/src/main/java/kr/or/teamserver/coinserver/service/DeviceServiceImpl.java
>      public void create(String token){
보통은 create 를 하고 나서 생성된 객체를 다시 넘겨주는게 좋아.
아이디를 포함한 객체로. 그래야 화면에서 생성된 애를 다시 조회하지 않아도 되니까.

2019-02-22 06:54 UTC, riyenas0925 commented on coin-server/src/main/java/kr/or/teamserver/coinserver/service/DeviceServiceImpl.java
>      public void create(String token){
@parkjonghyeob 
아하 넵 알겠습니다

2019-02-22 06:54 UTC, merged