세탁기 id 설정 추가 , loop문 딜레이 수정(10s -> 1s), clcd 딜레이 삭제
sejong-interface/2018-Winter-Project pull request #27
Opened 2019-02-16 07:44 UTC by riyenas0925

세탁기 id  추가
* /arduino/{id}

loop문 딜레이 수정
* 10초 -> 1초

clcd 딜레이 삭제
* 3초 -> 0초

2019-02-16 07:56 UTC, parkjonghyeob requested changes

2019-02-16 07:56 UTC, parkjonghyeob commented on coin-arduino/project/project.ino
> +  cmd.concat("POST " + address + (String)washerId + " HTTP/1.1\r\n");
`(String) washerId`

2019-02-16 14:55 UTC, riyenas0925 commented
@parkjonghyeob 수정했습니다

2019-02-18 10:05 UTC, parkjonghyeob approved these changes
수고했어~! 👍 👍

2019-02-18 10:58 UTC, merged