안드로이드 서버 데이터 파싱 오류 수정, 날씨 데이터 파싱 구현
sejong-interface/2018-Winter-Project pull request #9
Opened 2019-02-04 04:51 UTC by jkey20

안드로이드 서버 데이터 파싱 오류 수정, 날씨 데이터 파싱 구현

제대로 올린지 모르겠네요 ㅎㅎ;

2019-02-06 04:42 UTC, parkjonghyeob commented
@jkey20 .idea/ 폴더의 파일은 전부 .gitignore 에 포함시켜줘.

2019-02-06 04:48 UTC, parkjonghyeob requested changes

2019-02-06 04:48 UTC, parkjonghyeob commented on MyApplication/app/build.gradle
> +
불필요한 공백들 제거

2019-02-06 04:48 UTC, parkjonghyeob commented on MyApplication/app/build.gradle
> +dependencies {
종류별로 보기 좋게 정렬~
compile
compile

implementation
implementation

androidTestCompile
androidTestCompile

2019-02-06 04:48 UTC, parkjonghyeob commented on MyApplication/app/src/main/java/com/example/jkey2/myapplication/Main2Activity.java
> +public class Main2Activity extends AppCompatActivity {
전체적으로 android studio 기본 코드 스타일 적용
`int value = 0;` 등 띄어쓰기가 전혀 안되어 있네~

2019-02-06 04:48 UTC, parkjonghyeob commented on MyApplication/app/src/main/java/com/example/jkey2/myapplication/MainActivity.java
> +
불필요한 공백 모든 파일에 제거

2019-02-06 04:48 UTC, parkjonghyeob commented on MyApplication/app/src/main/java/com/example/jkey2/myapplication/MainActivity.java
> +        Button bt = (Button)findViewById(R.id.bt1);
Button bt <- 무슨 버튼인지 이름을 명확히

2019-02-06 04:48 UTC, parkjonghyeob commented on MyApplication/app/src/main/res/values/strings.xml
> +    <string name="app_name">My Application</string>
Application 이름 정확히 작성

2019-02-06 04:49 UTC, parkjonghyeob commented
불필요한 파일이 너무 많이 올라가 있네.
네가 만든 *.java, .xml 파일들만 올라가도록 모두 제거해서 다시 올려주면 좋겠어~

2019-02-08 09:19 UTC, soobin99 approved these changes

2019-02-09 10:22 UTC, closed without merging